---
# handlers file for errbot

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Check errbot config
  shell: "{{ errbot_virtualenv }}/bin/python -m py_compile {{ errbot_root }}/config.py"

- name: Restart errbot
  ansible.builtin.systemd:
    name: "{{ errbot_systemd_name }}"
    state: restarted
  become: yes
